name: shared_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shared_dart_sependancies:
    path: ../../shared_dart_sependancies
  core:
    path: ../../core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
